### ISSUE TITLE
Auto-timer on win/lose screens

### ISSUE THREAD

**Issue by moboid** [moboid/SUGAR#3]
Put a [30 second] timer on the Win and Lose screens.  After the timer runs out, the game goes to the Start screen.
This game restart should also force a fan stop (in case the game has triggered the bug where the fans don't stop running at the end of a play session.)

**Comment by zephlord** [comment]
in the draw() function of WinSreen.pde and LoseScreen.pde, add
```
    if (millis() - delayTimer > 30000)
          SwitchToScreen(TITLE_SCREEN);
```

**Comment by moboid** [comment]
It works!
