### ISSUE TITLE
Stop the blinking of "READY!"

### ISSUE THREAD

**Issue by moboid** [moboid/SUGAR#5]
Since the game now detects player input during the whole READY! cycle, the text should no longer blink.  So it needs some other kind of animation, perhaps the text is bolded and unbolded or italicized and unitalicized?

**Comment by zephlord** [comment]
Created a new font using Tools -> create font
Named the font "ready-alt-font.vlw" and stored it in the data folder. If you would like to use a different font, you can use Tools -> create font to create a different one and move it to the data folder, then change SUGAR.pde line 94 to read `readyAltFont = loadFont("<your-font-name-here>");`

Horse.pde lines 413 - 418 control the font displayed. Half the time it is one font, half the other font. This reuses the system in place for causing the blinking. the value `a` is a fluctuating value between 255 and 0. It was used to make the text fade and reappear, so we will use it to determine when to change fonts.

**Comment by moboid** [comment]
I didn't know it was using a 0-255 scale, and thought it was just on/off. I apologize for what seems a reversal, but it would be better if the technique goes back to text fade, but just does not ever go to 0 so that the text is never invisible.  (something like modulating back and forth between 128 <--> 255 might work?)  However - before doing another change we should talk about it to make sure i understand what is possible (and what's visible).
If it's easy enough for me to compare changes and reverse this snippet of code (lines 413-418) then I can do that.

**Comment by moboid** [comment]
Update: I can't quite figure out whether/how to make the pulsing happen, so, going (for now) with the font change.

**Comment by moboid** [comment]
Currently two related issues:
1. the font is still blinking, but using the new font instead of the consistent original font.
2. the "Pas de deux" text at the upper left of the screen is appearing in the new font, but because of it's different size, it's not displaying properly.   (I think we should just comment out the Pas de deux text?  it's kind of pointless.)

**Comment by moboid** [comment]
I will try to track down the shapetween info.  The person who made it is a friend, and ex-CMU (golan camp) person, Lee Byron.  Here's him talking about it, at the time:
https://processing.org/discourse/beta/num_1191032076.html

**Comment by moboid** [comment]
Further debugging info:  at the beginning of the game, the Pas de Deux text is in the correct font.  It is only when the horses get to their performance spot that this bit of text changes into the new/alternate font.  (and then stays that way the rest of the gameplay performance screen)

**Comment by moboid** [comment]
Holy shit i just realized you went in and fixed it already.
